# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update dailySex

on:
# 国际标准时间2点（北京时间10点）
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd code
        python -m pip install --upgrade pip
        pip install chardet fake_useragent
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Runner
      run: |
       mkdir pic
       cd code
       python 草榴_P_auto.py
       zip -r pic_$(date +"%Y-%m-%d").zip pic
       mv pic.zip ../pic.zip
       cd ..
    - name: Commit
      run: |
          git diff
          git config --global user.email 791751568@qq.com
          git config --global user.name adminlove520
          git add pic_$(date +"%Y-%m-%d").zip
          git commit -m "每日涩涩（`date +'%Y-%m-%d'`）"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ github.token }}

  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 7
